#%RAML 1.0
title: Example with headers
traits:
  numerable:
    headers:
      X-Dept:
        type: number
        multipleOf: 2.5
        minimum: 1
        maximum: 10

/users:
  get:
    is: [ numerable ]
    headers:
      X-Dept:
        examples:
          one: 5.0
          two: 4.0
          three: 11.0
